version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
clone_depth: 5
init:
- ps: "if($($env:APPVEYOR))\n{ \n$timeZone = [TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, \"Turkey Standard Time\");\n[datetime]$DateTime = $timeZone.ToString();\n\n$year = $DateTime.ToString(\"y.\").TrimEnd('.');\n$buildYear = (($year - 17) + 1);\n$buildTime = $DateTime.ToString(\"M.d.hmm\");\n$newBuildNumber = \"$buildYear.$buildTime\";\n\nUpdate-AppveyorBuild -Version $newBuildNumber;\n}\nelse\n{\n    Write-Host \"AppVeyor was not detected\";\n}"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
cache: packages
build_script:
- ps: "if($($env:APPVEYOR))\n{ \n    $SVersion = $($env:APPVEYOR_BUILD_VERSION);\n    Write-Host \"BaseMvvm.XamarinForms Version:$SVersion\";\n\n.\\nuget restore BaseMvvm.XamarinForms.sln;\n    $msbuild = \"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\amd64\\MSBuild.exe\"\n    & $msbuild BaseMvvm.XamarinForms.sln /property:Configuration=Release\n\n    .\\nuget pack BaseMvvm.XamarinForms.nuspec -version $SVersion;\n\n    Push-AppveyorArtifact \"$($env:APPVEYOR_BUILD_FOLDER)\\BaseMvvm.XamarinForms.$SVersion.nupkg\" -FileName \"BaseMvvm.XamarinForms.$SVersion.nupkg\" -DeploymentName \"NugetPackage1\";\n}\nelse\n{\n    Write-Host \"AppVeyor was not detected\";\n}"
test: off